// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAP6weJ1wYM0EDrwWm-0eThRLjofzFR8c',
    appId: '1:714785689884:web:ae566fa1193c081d226ad9',
    messagingSenderId: '714785689884',
    projectId: 'flutterplaygroundbookingapp',
    authDomain: 'flutterplaygroundbookingapp.firebaseapp.com',
    storageBucket: 'flutterplaygroundbookingapp.firebasestorage.app',
    measurementId: 'G-2JL8VK3FMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVYL8pgLG6XsAC7EJzsZ0EXxfvik0UZ0',
    appId: '1:714785689884:android:c7fdaf90dbdce30b226ad9',
    messagingSenderId: '714785689884',
    projectId: 'flutterplaygroundbookingapp',
    storageBucket: 'flutterplaygroundbookingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmPBDkQ9P33Y8dQXgMrb7tT0uaq9HpVcg',
    appId: '1:714785689884:ios:bfd71bb13b1da3d8226ad9',
    messagingSenderId: '714785689884',
    projectId: 'flutterplaygroundbookingapp',
    storageBucket: 'flutterplaygroundbookingapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterPlaygroundBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmPBDkQ9P33Y8dQXgMrb7tT0uaq9HpVcg',
    appId: '1:714785689884:ios:bfd71bb13b1da3d8226ad9',
    messagingSenderId: '714785689884',
    projectId: 'flutterplaygroundbookingapp',
    storageBucket: 'flutterplaygroundbookingapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterPlaygroundBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAP6weJ1wYM0EDrwWm-0eThRLjofzFR8c',
    appId: '1:714785689884:web:4d4ba999e05085fc226ad9',
    messagingSenderId: '714785689884',
    projectId: 'flutterplaygroundbookingapp',
    authDomain: 'flutterplaygroundbookingapp.firebaseapp.com',
    storageBucket: 'flutterplaygroundbookingapp.firebasestorage.app',
    measurementId: 'G-16TVM5Q034',
  );
}
